/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as DailiesRouteImport } from './routes/dailies'
import { Route as RubricRouteImport } from './routes/rubric'
import { Route as TimelineRouteImport } from './routes/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const DailiesRoute = DailiesRouteImport.update({
  id: '/dailies',
  path: '/dailies',
  getParentRoute: () => rootRouteImport,
} as any)
const RubricRoute = RubricRouteImport.update({
  id: '/rubric',
  path: '/rubric',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/canvas': typeof CanvasRoute
  '/dailies': typeof DailiesRoute
  '/rubric': typeof RubricRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/canvas': typeof CanvasRoute
  '/dailies': typeof DailiesRoute
  '/rubric': typeof RubricRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/canvas': typeof CanvasRoute
  '/dailies': typeof DailiesRoute
  '/rubric': typeof RubricRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent' | '/canvas' | '/dailies' | '/rubric' | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent' | '/canvas' | '/dailies' | '/rubric' | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/canvas'
    | '/dailies'
    | '/rubric'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  CanvasRoute: typeof CanvasRoute
  DailiesRoute: typeof DailiesRoute
  RubricRoute: typeof RubricRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dailies': {
      id: '/dailies'
      path: '/dailies'
      fullPath: '/dailies'
      preLoaderRoute: typeof DailiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rubric': {
      id: '/rubric'
      path: '/rubric'
      fullPath: '/rubric'
      preLoaderRoute: typeof RubricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  CanvasRoute: CanvasRoute,
  DailiesRoute: DailiesRoute,
  RubricRoute: RubricRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
